"""
pipeline/steps/gcode_gen_step.py - Native PipelineStep for GCode generation

Reimplements the logic of pipeline.gcode_gen.generate_gcode directly,
without calling the original function.

Data transport via ImageContext
--------------------------------
Reads   ctx.intermediates["paths"]        - List of (N, 2) arrays
        ctx.intermediates["binary"]       - uint8 array (H, W); provides image_shape
        ctx.intermediates["image_shape"]  - (H, W) as fallback if "binary" is missing
Writes  ctx.intermediates["gcode_lines"]  - List of GCode lines
"""

from __future__ import annotations

import logging
from typing import Iterator

from pipeline.core.base import ImageContext, PipelineStep

logger = logging.getLogger(__name__)


def filter_gcode(lines: list[str]) -> Iterator[str]:
    """Yields only executable GCode lines (no blank lines, no comments)."""
    for raw in lines:
        stripped = raw.strip()
        if not stripped:
            continue
        # Strip inline comments
        if ";" in stripped:
            code_part = stripped[: stripped.index(";")].strip()
        else:
            code_part = stripped
        if code_part:
            yield code_part


# Backward-compatible alias (imported directly in tests)
_filter_gcode = filter_gcode


class GCodeGenStep(PipelineStep):
    """
    Native GCode generation step - paths → GRBL GCode lines.

    Coordinate transformation:
      Image coordinate system:   Origin top-left,    Y down
      Plotter coordinates:       Origin bottom-left, Y up (standard GCode)
      → Y is mirrored: y_mm = origin_y + scale * (img_height - py)
      → X runs normally:  x_mm = origin_x + scale * px

    config keys             Default         Corresponds to CLI flag
    ---------------------------------------------------------------
    target_width_mm         180.0           --width
    target_height_mm        250.0           --height
    origin_x                5.0             --origin-x
    origin_y                5.0             --origin-y
    keep_aspect             True            --keep-aspect
    feedrate_draw           1500            --feedrate-draw
    feedrate_travel         3000            --feedrate-travel
    pen_down_cmd            "M3 S1000"      --pen-down-cmd
    pen_up_cmd              "M5"            --pen-up-cmd
    pen_delay_ms            100             --pen-delay-ms
    """

    name = "Generate G-code (legacy)"

    def process(self, ctx: ImageContext) -> ImageContext:
        c = self.config
        logger.info("GCodeGenStep — target=%.0fx%.0f mm, feedrate_draw=%s, feedrate_travel=%s",
                     float(c.get("target_width_mm", 180.0)),
                     float(c.get("target_height_mm", 250.0)),
                     c.get("feedrate_draw", 1500),
                     c.get("feedrate_travel", 3000))

        paths = ctx.intermediates["paths"]

        # "binary" provides the image size; alternatively passed directly as "image_shape"
        binary = ctx.intermediates.get("binary")
        if binary is not None:
            img_h, img_w = binary.shape[:2]
        else:
            img_h, img_w = ctx.intermediates["image_shape"]

        target_width_mm: float = float(c.get("target_width_mm", 180.0))
        target_height_mm: float = float(c.get("target_height_mm", 250.0))
        origin_x: float = float(c.get("origin_x", 5.0))
        origin_y: float = float(c.get("origin_y", 5.0))
        keep_aspect: bool = bool(c.get("keep_aspect", True))
        feedrate_draw: int = int(c.get("feedrate_draw", 1500))
        feedrate_travel: int = int(c.get("feedrate_travel", 3000))
        pen_down_cmd: str = str(c.get("pen_down_cmd", "M3 S1000"))
        pen_up_cmd: str = str(c.get("pen_up_cmd", "M5"))
        pen_delay_ms: int = int(c.get("pen_delay_ms", 100))

        # Scaling factor (px → mm)
        if keep_aspect:
            scale_uniform = min(target_width_mm / img_w, target_height_mm / img_h)
            scale_x = scale_uniform
            scale_y = scale_uniform
            actual_w = img_w * scale_uniform
            actual_h = img_h * scale_uniform
        else:
            scale_x = target_width_mm / img_w
            scale_y = target_height_mm / img_h
            actual_w = target_width_mm
            actual_h = target_height_mm

        def px_to_mm(px: float, py: float) -> tuple[float, float]:
            x_mm = origin_x + px * scale_x
            # Y mirroring: image origin top-left, plotter origin bottom-left
            y_mm = origin_y + (img_h - py) * scale_y
            return round(x_mm, 3), round(y_mm, 3)

        logger.debug(
            "GCodeGenStep: Image %dx%d px → drawing area %.1f×%.1f mm  (origin %.1f,%.1f mm)",
            img_w, img_h, actual_w, actual_h, origin_x, origin_y,
        )

        lines: list[str] = []

        # ---------- Header / Initialization ----------
        lines.append("; GCode generated by img2gcode")
        lines.append(f"; Image: {img_w}x{img_h}px  →  {actual_w:.1f}x{actual_h:.1f}mm")
        lines.append(f"; Paths: {len(paths)}")
        lines.append(f"; Draw feedrate: {feedrate_draw} mm/min")
        lines.append(f"; Travel feedrate: {feedrate_travel} mm/min")
        lines.append("")
        lines.append("G21         ; Unit: millimeters")
        lines.append("G90         ; Absolute coordinates")
        lines.append(f"G1 F{feedrate_travel}  ; Travel speed")
        lines.append(pen_up_cmd + "  ; Pen up (initialization)")
        lines.append("")

        # ---------- Homing / Start position ----------
        lines.append(f"G1 X{origin_x:.3f} Y{origin_y:.3f}  ; Start position")
        lines.append("")

        # ---------- Draw paths ----------
        total_moves = 0
        for path_idx, path in enumerate(paths):
            if len(path) < 2:
                continue

            x0, y0 = px_to_mm(float(path[0][0]), float(path[0][1]))
            lines.append(f"; Path {path_idx + 1}/{len(paths)}")
            lines.append(f"G1 X{x0:.3f} Y{y0:.3f} F{feedrate_travel}  ; Travel")

            lines.append(pen_down_cmd)
            if pen_delay_ms > 0:
                lines.append(f"G4 P{pen_delay_ms}  ; Wait for pen")
            lines.append(f"G1 F{feedrate_draw}")

            for pt in path[1:]:
                x, y = px_to_mm(float(pt[0]), float(pt[1]))
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
                total_moves += 1

            lines.append(pen_up_cmd)
            lines.append("")

        # ---------- Completion ----------
        lines.append("; Done - pen up and return to start position")
        lines.append(pen_up_cmd)
        lines.append(f"G1 X{origin_x:.3f} Y{origin_y + actual_h:.3f} F{feedrate_travel}  ; Paper advance")
        lines.append("")

        logger.debug("GCodeGenStep: %d lines, %d draw moves", len(lines), total_moves)
        ctx.intermediates["gcode_lines"] = lines
        return ctx


# ---------------------------------------------------------------------------
# Standalone function (formerly pipeline.gcode_gen.generate_gcode)
# ---------------------------------------------------------------------------

def generate_gcode(
    paths: list,
    image_shape: tuple[int, int],
    target_width_mm: float = 180.0,
    target_height_mm: float = 250.0,
    origin_x: float = 5.0,
    origin_y: float = 5.0,
    keep_aspect: bool = True,
    feedrate_draw: int = 1500,
    feedrate_travel: int = 3000,
    pen_down_cmd: str = "M3 S1000",
    pen_up_cmd: str = "M5",
    pen_delay_ms: int = 100,
) -> list[str]:
    """Generates GRBL GCode lines from a path list.

    Wrapper around ``GCodeGenStep`` for direct function call.

    Args:
        paths: List of (N, 2) arrays with pixel coordinates
        image_shape: ``(H, W)`` of source image in pixels
        target_width_mm: Drawing area width in mm
        target_height_mm: Drawing area height in mm
        origin_x: X origin of drawing area in mm
        origin_y: Y origin of drawing area in mm
        keep_aspect: Maintain aspect ratio
        feedrate_draw: Feedrate when drawing (mm/min)
        feedrate_travel: Feedrate when traveling (mm/min)
        pen_down_cmd: GCode command to lower the pen
        pen_up_cmd: GCode command to raise the pen
        pen_delay_ms: Wait time after lowering pen (ms)

    Returns:
        List of GCode lines as strings
    """
    from pipeline.core.base import ImageContext

    ctx = ImageContext()
    ctx.intermediates["paths"] = paths
    # Pass image_shape directly as tuple - no dummy array needed
    ctx.intermediates["image_shape"] = image_shape

    step = GCodeGenStep(config={
        "target_width_mm":  target_width_mm,
        "target_height_mm": target_height_mm,
        "origin_x":         origin_x,
        "origin_y":         origin_y,
        "keep_aspect":      keep_aspect,
        "feedrate_draw":    feedrate_draw,
        "feedrate_travel":  feedrate_travel,
        "pen_down_cmd":     pen_down_cmd,
        "pen_up_cmd":       pen_up_cmd,
        "pen_delay_ms":     pen_delay_ms,
    })
    ctx = step.process(ctx)
    return ctx.intermediates["gcode_lines"]
