; GCode generated by img2gcode
; Image: 512x512px  →  180.0x180.0mm
; Paths: 0
; Draw feedrate: 1500 mm/min
; Travel feedrate: 3000 mm/min

G21         ; Unit: millimeters
G90         ; Absolute coordinates
G1 F3000  ; Travel speed
M5  ; Pen up (initialization)

G1 X5.000 Y5.000  ; Start position

; Done - pen up and return to start position
M5
G1 X5.000 Y185.000 F3000  ; Paper advance
